//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherThemeTool {
  using System;
  
  
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Strings {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnotherThemeTool.Strings", typeof(Strings).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 	&lt;Compile Include=&quot;{inc}&quot;&gt;
    ///		&lt;Link&gt;{link}&lt;/Link&gt;{deps}
    ///	&lt;/Compile&gt;
    ///.
    /// </summary>
    internal static string CompileElement0 {
      get {
        return ResourceManager.GetString("CompileElement0", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 	&lt;Compile Include=&quot;{inc}&quot;&gt;
    ///		&lt;Link&gt;{link}&lt;/Link&gt;{deps}
    ///	&lt;/Compile&gt;
    ///.
    /// </summary>
    internal static string CompileElement1 {
      get {
        return ResourceManager.GetString("CompileElement1", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///        &lt;{tag} Include=&quot;{inc}&quot;&gt;
    ///            &lt;Link&gt;{fname:pre}\{fname}&lt;/Link&gt;{vals}
    ///        &lt;/{tag}&gt;.
    /// </summary>
    internal static string CompileElement2 {
      get {
        return ResourceManager.GetString("CompileElement2", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Argument ‘{0}’ as allready been added to the Dictionary..
    /// </summary>
    internal static string DictionaryList_ErrorMessage {
      get {
        return ResourceManager.GetString("DictionaryList_ErrorMessage", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to DictionaryList Usage Error.
    /// </summary>
    internal static string DictionaryList_ErrorMessage_Title {
      get {
        return ResourceManager.GetString("DictionaryList_ErrorMessage_Title", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;error Message=&quot;You probably need to select a project.&quot; /&gt;.
    /// </summary>
    internal static string ErrorSelectAProject {
      get {
        return ResourceManager.GetString("ErrorSelectAProject", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///            &lt;{0}&gt;{1}&lt;/{0}&gt;.
    /// </summary>
    internal static string FormatTag0 {
      get {
        return ResourceManager.GetString("FormatTag0", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to     &lt;ItemGroup&gt;@{nodes}
    ///    &lt;/ItemGroup&gt;
    ///.
    /// </summary>
    internal static string ItemGroupElement {
      get {
        return ResourceManager.GetString("ItemGroupElement", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No Project!.
    /// </summary>
    internal static string MsgNoProject {
      get {
        return ResourceManager.GetString("MsgNoProject", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to DependentUpon.
    /// </summary>
    internal static string TagDependentUpon {
      get {
        return ResourceManager.GetString("TagDependentUpon", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Link.
    /// </summary>
    internal static string TagLink {
      get {
        return ResourceManager.GetString("TagLink", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///&lt;div class=&apos;xpopup&apos;&gt;
    ///
    ///	&lt;span style=&apos;float:right&apos;&gt;&lt;input pickupid=&apos;{Pickup_ID}&apos; type=&apos;button&apos; value=&apos;edit&apos; id=&apos;editbutton&apos; /&gt;&lt;/span&gt;
    ///	
    ///	&lt;div class=&apos;addr&apos; style=&apos;float:left&apos;&gt;
    ///		&lt;font size=&apos;4&apos;&gt;&lt;b&gt;{Pickup_Name}&lt;/b&gt;&lt;/font&gt;&lt;br /&gt;
    ///		&lt;font size=&apos;1&apos;&gt;{addrStreet} {addrSuite}&lt;br /&gt;
    ///		{addrCity} {addrState} {addrZip}&lt;/font&gt;
    ///    &lt;/div&gt;
    ///    
    ///    &lt;div class=&apos;phone&apos; style=&apos;float:left;&apos;&gt;
    ///		&lt;table style=&apos;border-collapse: collapse; min-width:120px;&apos;&gt;
    ///			&lt;tr&gt;&lt;td&gt;{Phone_1}&lt;/td&gt;&lt;/tr&gt;
    ///			&lt;tr&gt;&lt;td&gt;{Phone_2}&lt;/td&gt;&lt;/tr&gt; [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string TestRow_Value {
      get {
        return ResourceManager.GetString("TestRow:Value", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
    ///&lt;config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
    ///  &lt;file-data&gt;D:\DEV\DATA\schema\Prime\prime.data.main.xdata&lt;/file-data&gt;
    ///  &lt;file-template&gt;D:\DEV\DATA\schema\Prime\NewPrimeTemplates4N.xtpl&lt;/file-template&gt;
    ///&lt;/config&gt;.
    /// </summary>
    internal static string XmlFile {
      get {
        return ResourceManager.GetString("XmlFile", resourceCulture);
      }
    }
  }
}
